### ISSUE TITLE
Error Loading Page nach installation

### ISSUE THREAD

**Issue by haujo** [christianTF/LoxBerry-Plugin-ALSATools#1]
Hallo,
ich habe auf einer frisch eingerichteten Loxberry Umgebung (Version: 0.2.3) das Plugin installiert. Wenn ich im Webfrontend auf das Plugin klicke, dann kommt nur die Meldung "Error Loading Page nach installation" und das Webfrontend erscheint nicht. Ich verwende einen Raspberry PI 3 Model B.

**Comment by christianTF** [comment]
Danke, ich schau mir das mal an,

Lg, Christian

**Comment by christianTF** [comment]
Fixed: https://github.com/christianTF/LoxBerry-Plugin-ALSATools/commit/af013f664a0244338d490f52bdf3120375eeaaff

Ich habe v0.1.2 auf die Download-Page geladen. Bitte nochmal installieren, LB rebooten, dann sollte es gehen!
lg, Christian

**Comment by haujo** [comment]
Vielen Dank jetzt funktioniert es!
